steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/huiswerk-maatje/huiswerk-maatje', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/huiswerk-maatje/huiswerk-maatje']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'huiswerk-maatje', '--image', 'gcr.io/huiswerk-maatje/huiswerk-maatje', '--region', 'europe-west4']
images:
- gcr.io/huiswerk-maatje/huiswerk-maatje